%%%
%%% paper2_plotSpinup.m
%%%
%%% Plots time series of melt rate across model resolutions, and maps FRIS
%%% melt rate.
%%% 

%%% Load reference experiment for parameters
expdir = '../experiments';
expname = 'hires_seq_onethird_RTOPO2';
loadexp;
rhoi = 934; %%% Density of ice

%%% Load experiments
expname_onethird_tides = 'hires_seq_onethird_RTOPO2';
expname_onethird_notides = 'hires_seq_onethird_notides_RTOPO2';
expname_onesixth_tides = 'hires_seq_onesixth_RTOPO2';
expname_onesixth_notides = 'hires_seq_onesixth_notides_RTOPO2';
expname_onetwelfth_tides = 'hires_seq_onetwelfth_RTOPO2';
expname_onetwelfth_notides = 'hires_seq_onetwelfth_notides_RTOPO2';
[tt_onethird_tides, ...
  SHImelt_onethird_tides, ...
  SHImelt_mean_onethird_tides, ...
  XC_onethird_tides, ...
  YC_onethird_tides, ...
  bathy_onethird_tides, ...
  icedraft_onethird_tides] ...
  = calcFRISMeltTimeSeries (expdir,expname_onethird_tides);
disp(1);
[tt_onethird_notides, ...
  SHImelt_onethird_notides, ...
  SHImelt_mean_onethird_notides, ...
  XC_onethird_notides, ...
  YC_onethird_notides, ...
  bathy_onethird_notides, ...
  icedraft_onethird_notides] ...
  = calcFRISMeltTimeSeries (expdir,expname_onethird_notides);
disp(2);
[tt_onesixth_tides, ...
  SHImelt_onesixth_tides, ...
  SHImelt_mean_onesixth_tides, ...
  XC_onesixth_tides, ...
  YC_onesixth_tides, ...
  bathy_onesixth_tides, ...
  icedraft_onesixth_tides] ...
  = calcFRISMeltTimeSeries (expdir,expname_onesixth_tides);
disp(3);
[tt_onesixth_notides, ...
  SHImelt_onesixth_notides, ...
  SHImelt_mean_onesixth_notides, ...
  XC_onesixth_notides, ...
  YC_onesixth_notides, ...
  bathy_onesixth_notides, ...
  icedraft_onesixth_notides] ...
  = calcFRISMeltTimeSeries (expdir,expname_onesixth_notides);
disp(4);
[tt_onetwelfth_tides, ...
  SHImelt_onetwelfth_tides, ...
  SHImelt_mean_onetwelfth_tides, ...
  XC_onetwelfth_tides, ...
  YC_onetwelfth_tides, ...
  bathy_onetwelfth_tides, ...
  icedraft_onetwelfth_tides] ...
  = calcFRISMeltTimeSeries (expdir,expname_onetwelfth_tides);
disp(5);
[tt_onetwelfth_notides, ...
  SHImelt_onetwelfth_notides, ...
  SHImelt_mean_onetwelfth_notides, ...
  XC_onetwelfth_notides, ...
  YC_onetwelfth_notides, ...
  bathy_onetwelfth_notides, ...
  icedraft_onetwelfth_notides] ...
  = calcFRISMeltTimeSeries (expdir,expname_onetwelfth_notides);
disp(6);


%%% Plotting options
fontsize = 14;
linewidth = 1.5;
latMin = min(min(YC_onetwelfth_tides));
latMax = -72;
lonMin = -80;
lonMax = -30;
bathycntrs = [0 250 500 1000 2000 3000 4000];

%%% Plot the time series
figure(202);
clf;
set(gcf,'Position',[131          93        1289         870]);

subplot('Position',[0.0760    0.5730    0.8774    0.3534]);
colororder = get(gca,'ColorOrder');
plot(tt_onethird_tides/t1year,-SHImelt_onethird_tides/1e12*t1year,'-','Color',colororder(1,:),'LineWidth',linewidth);
hold on;
plot((tt_onesixth_tides+9*t1year)/t1year,-SHImelt_onesixth_tides/1e12*t1year,'-','Color',colororder(2,:),'LineWidth',linewidth);
plot((tt_onetwelfth_tides+18*t1year)/t1year,-SHImelt_onetwelfth_tides/1e12*t1year,'-','Color',colororder(3,:),'LineWidth',linewidth);
plot(tt_onethird_notides/t1year,-SHImelt_onethird_notides/1e12*t1year,'--','Color',colororder(1,:),'LineWidth',linewidth);
plot((tt_onesixth_notides+9*t1year)/t1year,-SHImelt_onesixth_notides/1e12*t1year,'--','Color',colororder(2,:),'LineWidth',linewidth);
plot((tt_onetwelfth_notides+18*t1year)/t1year,-SHImelt_onetwelfth_notides/1e12*t1year,'--','Color',colororder(3,:),'LineWidth',linewidth);
hold off;
set(gca,'XLim',[18 27]);
set(gca,'Ylim',[90 250]);
xlabel('Model Integration Time (years)','interpreter','latex');
ylabel('FRIS Melt (Gt/yr)','interpreter','latex');
set(gca,'FontSize',fontsize);
handle = legend(gca,'1/3^o','1/6^o','1/12^o');
set(handle,'Orientation','Horizontal');
set(handle,'Position',[0.2690    0.8778    0.2073    0.04]);

ax1 = gca;
ax2 = axes('Position',get(ax1,'Position'));
plot(tt_onethird_notides/t1year+2007-18,0*tt_onethird_notides,'k-','LineWidth',0.5);
hold on;
plot(tt_onethird_notides/t1year+2007-18,0*tt_onethird_notides,'k--','LineWidth',0.5);
hold off;
set(ax2,'Color','None');
set(ax2,'XAxisLocation','Top');
set(ax2,'YLim',get(ax1,'YLim'));
set(ax2,'YTick',[]);
box off;
set(ax2,'XLim',[2007 2016]);
set(ax2,'FontSize',fontsize);
set(get(ax2,'XLabel'),'String','Equivalent calendar year','interpreter','latex');
handle = legend(ax2,'Tides','No tides');
set(handle,'Orientation','Horizontal');
set(handle,'Color','w');
set(handle,'Position',[0.7262    0.8815    0.1684    0.0380]);

SHImelt_mean_onetwelfth_tides(icedraft_onetwelfth_tides-bathy_onetwelfth_tides<=0) = NaN;
subplot('Position',[0.03 0.0 0.43 0.46]);
axesm('eqaconicstd',...
  'fontsize',13,...
  'Grid','on', ...    
  'Frame','off', ...
  'MapLatLimit',[latMin latMax], ...
  'MapLonLimit',[lonMin lonMax], ... 
  'MapParallels',[-85 -65], ...
  'PLineLocation', 5, ...
  'MLineLocation', 10,...
  'MeridianLabel', 'on', ...
  'ParallelLabel', 'on');    %, ...
%           'origin',[yc(round(size(yc,1)/2),round(size(yc,2)/2)),xc(round(size(xc,1)/2),round(size(xc,2)/2))])
axis off;
setm(gca,'MLabelParallel',-20)
pcolorm(YC_onetwelfth_tides,XC_onetwelfth_tides,-SHImelt_mean_onetwelfth_tides/rhoi*t1year);
shading interp;
caxis([-5 5]);
% colormap redblue;
colormap(cmocean('balance',100));
hold on;
[cs,C] = contourm(YC_onetwelfth_tides,XC_onetwelfth_tides,icedraft_onetwelfth_tides-bathy_onetwelfth_tides,bathycntrs,'EdgeColor',[.7 .7 .7]); 
hh = clabelm(cs,C,'LabelSpacing',800,'TextColor',[.7 .7 .7]);
set (hh,'fontsize',8,'BackgroundColor','none','Edgecolor','none')
hold off; 
% tightmap;
h = title('1/12$^\circ$, Tides','interpreter','latex','Fontsize',fontsize+4);
% set(h,'Position',[0 .9 0])


SHImelt_mean_onetwelfth_notides(icedraft_onetwelfth_notides-bathy_onetwelfth_notides<=0) = NaN;
plotpos = [0.47 0.0 0.43 0.46];
subplot('Position',plotpos);
axesm('eqaconicstd',...
  'fontsize',13,...
  'Grid','on', ...    
  'Frame','off', ...
  'MapLatLimit',[latMin latMax], ...
  'MapLonLimit',[lonMin lonMax], ... 
  'MapParallels',[-85 -65], ...
  'PLineLocation', 5, ...
  'MLineLocation', 10,...
  'MeridianLabel', 'on', ...
  'ParallelLabel', 'on');    %, ...
%           'origin',[yc(round(size(yc,1)/2),round(size(yc,2)/2)),xc(round(size(xc,1)/2),round(size(xc,2)/2))])
axis off;
setm(gca,'MLabelParallel',-20)
pcolorm(YC_onetwelfth_notides,XC_onetwelfth_notides,-SHImelt_mean_onetwelfth_notides/rhoi*t1year);
shading interp;
caxis([-5 5]);
% colormap redblue;
colormap(cmocean('balance',100));
hold on;
[cs,C] = contourm(YC_onetwelfth_tides,XC_onetwelfth_tides,icedraft_onetwelfth_tides-bathy_onetwelfth_tides,bathycntrs,'EdgeColor',[.7 .7 .7]); 
hh = clabelm(cs,C,'LabelSpacing',800,'TextColor',[.7 .7 .7]);
set (hh,'fontsize',8,'BackgroundColor','none','Edgecolor','none')
hold off; 
% tightmap
% set(gca,'Position',plotpos);
h = title('1/12$^\circ$, No tides','interpreter','latex','Fontsize',fontsize+4);




%%% Add colorbar and title
h = colorbar;
set(h,'Position',[0.92 0.02 0.015 .38])
set(h,'FontSize',fontsize);
set(h,'YTick',[-5:2.5:5]);
title(h,'m/yr','Fontsize',fontsize,'interpreter','tex');


annotation('textbox',[0.02 0.5 0.05 0.05],'String','(a)','interpreter','latex','FontSize',fontsize+2,'LineStyle','None');
annotation('textbox',[0.05 0.05 0.05 0.05],'String','(b)','interpreter','latex','FontSize',fontsize+2,'LineStyle','None');
annotation('textbox',[0.5 0.05 0.05 0.05],'String','(c)','interpreter','latex','FontSize',fontsize+2,'LineStyle','None');

